# @name create-link
POST http://localhost:3333/api/links
Content-Type: 'application/json'

{
  "code": "rocketseat",
  "url": "http://rocketseat.com.br"
}

###
# @name list-links
GET http://localhost:3333/api/links
 

###
# @name use-link
GET http://localhost:3333/rocketseat
 